# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LPPhotoViewerSample' do

pod 'SDWebImage', '~> 4'
pod 'SDWebImage/GIF', '~> 4'

end

